# Configuration Port
server:
  port: 8081

# Configuration Thymeleaf
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    cache: false

  # Configuration Devtools
  devtools:
    livereload:
      enabled: true
    restart:
      enable: false

  # Configuration PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: orderuser
    password: 1234

  # Application name
  application:
    name: order

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

# Configuration mybatis
#mybatis:
#  mapper-locations: classpath:sqlmapper/**/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
